Add descriptions to the tasks data API
opencv/cvat pull request #5945
Opened 2023-03-27 20:24 UTC by zhiltsov-max

### Motivation and context

- Added descriptions for the server task data API fields
- Fixed docs

### How has this been tested?

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

2023-03-31 17:05 UTC, SpecLad requested changes

2023-03-31 17:05 UTC, SpecLad commented on site/content/en/docs/manual/basics/create_an_annotation_task.md
> +To save and open the task click **Submit & Open** .
```suggestion
To save and open the task, click **Submit & Open** .
```

2023-03-31 17:05 UTC, SpecLad commented on site/content/en/docs/manual/basics/create_an_annotation_task.md
> +To create several tasks in sequence, click on the **Submit & Continue**.
```suggestion
To create several tasks in sequence, click **Submit & Continue**.
```

2023-03-31 17:59 UTC, zhiltsov-max commented on cvat/apps/engine/serializers.py
> +        help_text="Files to be uploaded")
Probably, all fields must be marked write-only

2023-04-03 09:26 UTC, zhiltsov-max commented on cvat/apps/engine/serializers.py
> +            sandbox and organization cloud storages can be used
> Both user sandbox and organization cloud storages can be used

@Marishka17, is it true at all? I suspect it's not supposed.

2023-04-03 13:44 UTC, SpecLad commented on site/content/en/docs/manual/advanced/data_on_fly.md
> +- The first access to the data will take more time
Ping? I think you missed this one.

2023-04-04 12:37 UTC, merged