analytics documentation updated
opencv/cvat pull request #6205
Opened 2023-05-26 18:09 UTC by mdacoca

### Motivation and context

### How has this been tested?

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

2023-05-29 14:17 UTC, azhavoro requested changes

2023-05-29 14:17 UTC, azhavoro commented on site/content/en/docs/administration/advanced/analytics.md
> +| organization    | organization ID or None                                                                 |
Please update the table to match the actual database schema https://github.com/opencv/cvat/blob/develop/components/analytics/clickhouse/init.sh

2023-05-29 14:17 UTC, azhavoro commented on site/content/en/docs/administration/advanced/analytics.md
> +| Mandatory Field | Description                                                                             |
```suggestion
| Field | Description                                                                             |
```

2023-05-29 14:17 UTC, azhavoro commented on site/content/en/docs/administration/advanced/analytics.md
> +Extra fields can be added to the JSON blob.
This is the description for the missing field `payload`. For example: payload is astringified JSON, which can contain any additional data.

2023-05-29 14:17 UTC, azhavoro commented on site/content/en/docs/administration/advanced/analytics.md
> +```json
It's not actually a json

2023-05-29 14:17 UTC, azhavoro commented on site/content/en/docs/administration/advanced/analytics.md
> +You can adjust the dashboards. To do this, click on the
It's good idea to add instruction how to adjust dashboards, let's disscuss offline.

2023-05-29 14:17 UTC, azhavoro commented on site/content/en/images/supported_events.png
please replace all images with jpeg, png is too big...

2023-05-31 08:45 UTC, azhavoro commented on site/content/en/docs/contributing/development-environment.md
> +```json
```suggestion
```yml
```

2023-05-31 08:51 UTC, azhavoro commented on site/content/en/docs/contributing/development-environment.md
> +**Or** remove the following data from
```suggestion
In addition, you can completely disable analytics if you don't need it by deleting the following data from
```

2023-05-31 08:56 UTC, azhavoro commented on site/content/en/images/dashboard_04.png
png -> jpg

2023-05-31 09:12 UTC, mdacoca commented on site/content/en/images/dashboard_03.jpg
sure

2023-05-31 09:32 UTC, azhavoro approved these changes

2023-05-31 18:28 UTC, merged