Bump Grafana version
opencv/cvat pull request #6912
Opened 2023-09-27 06:58 UTC by pktiuk

Currently Grafana supports 4 major versions: `10.1.x`, `10.0.x`, `9.5.x` and `9.4.x`.   
`9.3.x` series is not supported anymore.

### Motivation and context

Having outdated and not supported version of Grafana may have negative impact on safety and performance, so I think at least an update to `9.4.x` series should be done

### How has this been tested?

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

2023-09-28 07:33 UTC, azhavoro requested changes
Please update the version for Helm as well 
https://github.com/opencv/cvat/blob/develop/helm-chart/Chart.yaml#L49

2023-09-28 07:59 UTC, pktiuk commented
@azhavoro Done

2023-10-03 15:29 UTC, azhavoro commented
@pktiuk thanks for the contribution

2023-10-03 15:29 UTC, azhavoro approved these changes

2023-10-04 09:12 UTC, merged