Remove unnecessary COUNT for labels
opencv/cvat pull request #6918
Opened 2023-09-28 08:33 UTC by nmanovic

Optimized /api/projects, /api/tasks, and /api/jobs requests. Previously for unification, we decided to add a count of labels into every response for each project, task, and job. It leads to performance issues. UI and probably other clients don't use the information because it is useless. Removing it, helps to optimize the SQL request several times.

2023-09-28 09:12 UTC, nmanovic commented
Before:
![image](https://github.com/opencv/cvat/assets/40690625/ca91834e-221c-4a1b-8cd1-3c69b21b83f8)


After:
![image](https://github.com/opencv/cvat/assets/40690625/437794ed-6925-46ca-81fc-1217a55f4d0d)

2023-09-28 10:47 UTC, SpecLad commented on cvat/apps/engine/views.py
>          'label_set__attributespec_set'
What about these label-related prefetches, are they needed?

2023-10-13 13:26 UTC, SpecLad requested changes

2023-10-13 13:26 UTC, SpecLad commented on tests/python/shared/fixtures/data.py
> +def jobs():  # jobs with labels count
Misplaced comment?

2023-10-13 13:26 UTC, SpecLad commented on tests/python/rest_api/test_tasks.py
> +        tasks = tasks_wlc
IMO, renamings like these serve to obscure the underlying data structure. If a variable is supposed to have label counts, then let it keep the `_wlc` suffix.

2023-10-13 13:28 UTC, SpecLad commented on changelog.d/20231011_162748_nikita_fix_perf_issues.md
> +  significantly complicates SQL queries.
It would be useful to mention how the users can get this information now.

2023-10-18 12:32 UTC, SpecLad approved these changes

2023-10-18 12:36 UTC, merged