Documentation retouch: cloud storages and mot data format
opencv/cvat pull request #7071
Opened 2023-10-27 08:12 UTC by mdacoca

- Added videos to Cloud Stirages
- Updated wording in Cloud Storages
- Updated data format for MOT Import

### Motivation and context

### How has this been tested?

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have created a changelog fragment 
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

2023-10-27 14:15 UTC, Marishka17 reviewed
We have `Attach storage to CVAT` for each provider, so I believe it would be better to insert video examples in each section and not create a new common section with examples at the end of the page. What do you think?

2023-10-27 14:15 UTC, Marishka17 commented on site/content/en/docs/manual/advanced/formats/format-mot.md
> -├── labels.txt # optional, mandatory for non-official labels
I guess we don't need to delete the comment

2023-10-30 12:55 UTC, Marishka17 commented
@mdacoca, Could you please recheck that the correct terms are used everywhere?

2023-10-30 13:44 UTC, mdacoca commented
> @mdacoca, Could you please recheck that the correct terms are used everywhere?

updated

2023-10-30 14:04 UTC, Marishka17 requested changes

2023-10-30 14:14 UTC, Marishka17 commented on site/content/en/docs/manual/basics/attach-cloud-storage.md
> +1. Go to [**AWS S3 cli**](https://aws.amazon.com/cli/) and run
```suggestion
1. Go to [**AWS CLI**](https://aws.amazon.com/cli/) and run
```

2023-10-31 11:03 UTC, Marishka17 approved these changes

2023-10-31 13:02 UTC, merged